spring:
  application:
    name: avis
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:file:./data/avisdb;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update

app:
  jwt:
    secret: "avis-app-secret-key-must-be-at-least-256-bits-long-for-hmac-sha256"
    expiration: 86400000
  admin:
    pseudo: admin
    password: admin123

server:
  port: 8081